---
title: "International"
author: "ruby"
date: "2024-10-10"
output: pdf_document
---
#Set-up
```{r}
library(data.table)
library(ggplot2)
library(patchwork)
library(lubridate)
```

```{r}
InternationalFatalities <- fread("CSV/international_roadfatal.csv")
InternationalFatalities <- InternationalFatalities[order(`Rate of road deaths in 2023 per million population`, decreasing = TRUE),]
```

```{r}
ggplot(InternationalFatalities, aes(y= `Rate of road deaths in 2023 per million population`, x= Country)) + 
  geom_bar(stat = "identity")+ 
  theme_classic() + 
  theme( axis.text.x=element_text(angle = 45, hjust=1), plot.title = element_text(face = "bold", hjust = 0.5)) + 
  ylab("Rate of road deaths") + 
  ggtitle("Rate of road deaths in 2023 per million population") + 
  xlab("Country")
```


```{r}
OECDStats <- fread("CSV/OECDInternationalFatalities.csv")
OECDStats <- OECDStats[order(OBS_VALUE, decreasing = TRUE),][, Reference := paste0(REF_AREA, "_", `Reference area`)]
```

```{r}
unique(OECDStats$Reference)
```
#Graphs
```{r}
ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + geom_line() + theme_classic() + ylab("Fatalities") + xlab("Date")
```
```{r}
ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "SWE")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "GBR")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "MEX"))+ 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "BIH")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "NOR")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "USA")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "CAN")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "AUS")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "NLD")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "FIN")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "JPN")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "ISL")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "CHE")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "MLT")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "IRL")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "DNK")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "NZL")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "FRA")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "DEU")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "ISR")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "AUT")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "BEL")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "TUR")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "GRC")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "MNE")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "HUN")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "ESP")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "POL")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "KOR")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "PRT")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "CZE")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "ROU")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "MKD")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "SVN")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "LVA")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "EST")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "CHL")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "GEO")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "AZE")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "ARM")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "MDA")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "UKR")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "LUX")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")

ggplot(data= OECDStats, aes(x = TIME_PERIOD , y= OBS_VALUE, colour = REF_AREA)) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "HRV")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "LTU")) + 
  geom_line(data = subset(OECDStats, OECDStats$REF_AREA == "BGR")) +   theme_classic()+ ylab("Fatalities") + xlab("Date")
```