---
title: "New data"
author: "ruby"
date: "2024-11-08"
output: pdf_document
---
#Set up
```{r}
if(!require("pacman")) install.packages("pacman")
pacman::p_load(data.table, lubridate, ggplot2, patchwork, readxl, readr, RACFfunctions, scales, utils)
options(scipen = 100)
```

```{r}
source("~/Documents/GitHub/RubyMotoringIndex/ForRuby.R")
```

```{r}
source("~/Documents/GitHub/SustainableMotoringIndex/KSIs/ColourFunction.R")
```


```{r}
MilesByVehicleType <- as.data.table(read_excel("~/Documents/GitHub/SustainableMotoringIndex/KSIs/tra0101-miles-by-vehicle-type.xlsx", sheet = "TRA0101", skip = 4))

download("https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatestimeseriesdataset/current/upload-pop.csv", "~/Documents/GitHub/RubyMotoringIndex/CSV/PopulationEst.csv")

Population <- fread("CSV/PopulationEst.csv")
Population <- Population[8:62,]
setnames(Population, c("Title", "Scotland population mid-year estimate", "Great Britain population mid-year estimate", "England population mid-year estimate", "England and Wales population mid-year estimate", "United Kingdom population mid-year estimate", "Northern Ireland population mid-year estimate", "Wales population mid-year estimate"), c("Year", "Scotland", "Great Britain", "England", "England and Wales", "United Kingdom", "Northern Ireland", "Wales"))
Population <- Population[, lapply(.SD, as.numeric), .SDcols = c("Scotland", "Great Britain", "England", "England and Wales", "United Kingdom", "Northern Ireland", "Wales"), by = c("Year")]

Population <- Population[, Year:=as.numeric(Year)]

TotalMilesDriven <- MilesByVehicleType[,.(Year, `All Motor Vehicles`)]
TotalMilesDriven <- TotalMilesDriven[, Year:=(as.Date(paste0(Year, "-01-01"), tryFormats = "%Y"))]

TotalMilesDriven <- merge(TotalMilesDriven, Population, by = "Year", all= TRUE)
TotalMilesDriven <- TotalMilesDriven[,"Population (GB)":=`Great Britain`]
TotalMilesDriven <- TotalMilesDriven[,.(Year, `All Motor Vehicles`, `Population (GB)`)]
```

```{r}
CasualtybyYear <- cas.df[collision_year < 2004 & !casualty_severity == "Slight", .N, keyby=c("collision_year", "casualty_severity")]

tester <- cas.df[collision_year>=2004 & !casualty_severity == "Fatal" & !(casualty_adjusted_severity_slight == 1), .(collision_year, casualty_severity, casualty_adjusted_severity_serious, casualty_adjusted_severity_slight)]

tester <- tester[,lapply(.SD, sum), .SDcols = c("casualty_adjusted_severity_serious"), by = c("collision_year")]
tester <- tester[, "casualty_severity":="Serious"]
setnames(tester, "casualty_adjusted_severity_serious", "N")

tester2 <- cas.df[collision_year>=2004 & casualty_severity == "Fatal", .(collision_year, casualty_severity, casualty_adjusted_severity_serious, casualty_adjusted_severity_slight)]
tester2 <- tester2[,.N, keyby = c("collision_year")]
tester2 <- tester2[, "casualty_severity":="Fatal"]

CasualtybyYear <- merge(CasualtybyYear, tester, by =c("collision_year", "casualty_severity", "N"), all = TRUE)
CasualtybyYear <- merge(CasualtybyYear, tester2, by =c("collision_year", "casualty_severity", "N"), all = TRUE)
rm(tester, tester2)

temp <- CasualtybyYear
temp <- temp[,lapply(.SD, sum), .SDcols = "N", by = "collision_year"][, "casualty_severity":="KSI"]
CasualtybyYear <- merge(CasualtybyYear, temp, by = c("collision_year", "N", "casualty_severity"), all = TRUE)
```

```{r}
KSIandMileage <- merge(MilesByVehicleType[,.(Year,`All Motor Vehicles`)], CasualtybyYear, by.x ="Year" , by.y = "collision_year", all = TRUE)
KSIandMileage <- KSIandMileage[!is.na(casualty_severity)]


KSIandMileage <- KSIandMileage[, "Rate":= N / `All Motor Vehicles`]
```

#Graphs 
```{r}
ggplot(KSIandMileage, aes(x = Year, y = N, colour = casualty_severity)) +
  geom_line() +
  theme_classic() +
  labs(title = "Casualties and fatalities by year", x = "Year", y = "Totals", caption = "In 2004 there was a change in methodology to improve the\n accuracy of the seriousness of injuries reported, adjusted severity rates are the \nresult of this, shown by the data on the right of the dotted line.") +
  scale_color_manual("", values = .CasualtyColours) +
    geom_vline(xintercept=2004, color="black", linewidth =0.5, linetype = "dashed") +
    scale_x_continuous(n.breaks = 10, expand=c(0,0)) + 
  scale_y_continuous(expand = c(0,0), labels = scales::comma, n.breaks = 10) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), axis.text.x=element_text(angle = 45, hjust=1), plot.caption = element_text(face = "italic"), legend.position = "bottom")
```

```{r}
ggplot(KSIandMileage, aes(x = Year, y = Rate, colour = casualty_severity, linetype = casualty_severity)) + 
  geom_line() + 
  theme_classic() + 
  scale_color_manual(" ", values = .CasualtyColours) + 
  scale_linetype_manual(" ", values = .CasualtyLines) +
  geom_vline(xintercept=2004, color="black", linewidth=0.2, linetype = "dashed") +
  scale_x_continuous(n.breaks = 10, expand=c(0,0)) + 
  scale_y_continuous(expand=c(0,0), labels = scales::comma, n.breaks = 10) +
  labs(x= "Year", y = "Casualties/ fatalities per billion miles", title = "Fatalities and serious injuries per one billion motor vehicle miles travelled", caption = "In 2004 there was a change in methodology to improve the accuracy of the seriousness of injuries reported. \nAdjusted severity rates are the result of this, shown by the data on the right of the dotted line.") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), axis.text.x=element_text(angle = 45, hjust=1), plot.caption = element_text(face = "italic"), legend.position = "bottom")
```


```{r}
ggplot(KSIandMileage[casualty_severity=="KSI",], aes(x = Year, y = Rate, colour = casualty_severity)) + 
  geom_line()+
  theme_classic() + 
  labs(title = "Fatalities and serious injuries per one billion motor vehicle miles", x = "Year", y = "Rate", caption = "In 2004 there was a change in methodology to improve the accuracy of the seriousness of injuries reported. \nAdjusted severity rates are the result of this, shown by the data on the right of the dotted line.") +
  scale_color_manual(" ", values = .CasualtyColours)  +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), axis.text.x=element_text(angle = 45, hjust=1), plot.caption = element_text(face = "italic"), legend.position = "bottom") +
    geom_vline(xintercept=2004, color="black", linewidth =0.5, linetype = "dashed") +
    scale_x_continuous(n.breaks = 10, expand=c(0,0)) + 
  scale_y_continuous(expand=c(0,0), labels = scales::comma, n.breaks = 10)
```
#Unadjusted KSI graph
```{r}
UnadjustedKSI <- cas.df[!casualty_severity=="Slight",.N, keyby = c("collision_year", "casualty_severity")]

temp <- UnadjustedKSI[, lapply(.SD, sum), .SDcols = "N", by = "collision_year"]
temp <- temp[, "casualty_severity":="KSI"]
UnadjustedKSI <- merge(UnadjustedKSI, temp, by = c("collision_year", "N", "casualty_severity"), all = TRUE)
rm(temp)

UnadjustedKSI <- merge(MilesByVehicleType[,.(Year, `All Motor Vehicles`)], UnadjustedKSI, by.x = "Year",  by.y = "collision_year", all = TRUE)
UnadjustedKSI <- UnadjustedKSI[!is.na(casualty_severity)]
UnadjustedKSI <- UnadjustedKSI[, "Rate":=N/`All Motor Vehicles`]

```


```{r}
ggplot(UnadjustedKSI, aes(x = Year, y = Rate, colour = casualty_severity, linetype = casualty_severity)) + 
  geom_line() +
  theme_classic() + 
  labs(title = "UNADJUSTED Fatalities and serious injuries per one billion motor vehicle miles travelled", x = "Year", y = "Casualties/ fatalities per billion miles") +
  scale_color_manual("", values = .CasualtyColours) + 
  scale_linetype_manual("", values = .CasualtyLines) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), axis.text.x=element_text(angle = 45, hjust=1), plot.caption = element_text(face = "italic"), legend.position = "bottom") + 
  scale_x_continuous(n.breaks = 10, expand=c(0,0)) + 
  scale_y_continuous(expand=c(0,0), labels = scales::comma, n.breaks = 10)
```


```{r}
ggplot(UnadjustedKSI[Year>=2004], aes(x = Year, y = Rate, colour = casualty_severity, linetype = casualty_severity)) + 
  geom_line() +
  theme_classic() + 
  labs(title = "UNADJUSTED Fatalities and serious injuries per one billion motor vehicle miles travelled", x = "Year", y = "Casualties/ fatalities per billion miles", subtitle = "2004 onwards") +
  scale_color_manual("", values = .CasualtyColours) + 
  scale_linetype_manual("", values = .CasualtyLines) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), axis.text.x=element_text(angle = 45, hjust=1), plot.caption = element_text(face = "italic"), legend.position = "bottom") + 
  scale_x_continuous(n.breaks = 10, expand=c(0,0)) + 
  scale_y_continuous(expand=c(0,0), labels = scales::comma, n.breaks = 10)
```


#KSIs by population
```{r}
PopulationKSIs <- merge(Population[,.(Year, `Great Britain`)], CasualtybyYear, by.x = "Year", by.y = "collision_year", all = TRUE)
PopulationKSIs <- PopulationKSIs[!is.na(casualty_severity)]
PopulationKSIs <- PopulationKSIs[, "Per capita":= N / (`Great Britain` / 100000)]

ggplot(PopulationKSIs, aes(x = Year, y = `Per capita`, colour = casualty_severity, linetype = casualty_severity)) + 
  geom_line() + 
  theme_classic() + labs(title = "Fatalities and serious injuries per 100k in GB Population", x = "Year", y = "Casualties/ fatalities per population", caption = "*In 2004 there was a change in methodology to improve the accuracy of the seriousness \n of injuries reported, adjusted severity rates are the result of this.") +
  scale_color_manual("", values = .CasualtyColours) + 
  scale_linetype_manual("", values = .CasualtyLines) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), axis.text.x=element_text(angle = 45, hjust=1), plot.caption = element_text(face = "italic"), legend.position = "bottom") + 
  geom_vline(xintercept=2004, color="black", linewidth=0.2, linetype = "dashed")  + 
  scale_x_continuous(n.breaks = 10, expand=c(0,0)) + 
  scale_y_continuous(expand=c(0,0), labels = scales::comma, n.breaks = 10)
```
# International comparison

```{r}
International <- as.data.table(read_excel("CSV/ras0404.xlsx", sheet = "Historic", skip = 4))
International <- International[, "Rate of road deaths in 2024 per million population":=as.numeric(`Rate of road deaths in 2024 per million population [note 3]`)][, "Country":= `Country [note 1]`]

International <- International[,.(Country,`Rate of road deaths in 2024 per million population`)]
```

```{r}
ggplot(International, aes(y= `Rate of road deaths in 2024 per million population`, x= Country)) + 
  geom_bar(stat = "identity", fill = .RACFColour1.1)+ 
  theme_classic() + 
  labs(title = "Rate of road deaths in 2024 per million population", x = "Country", y= "Rate of road deaths") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), axis.text.x=element_text(angle = 45, hjust=1), plot.caption = element_text(face = "italic"), legend.position = "bottom") + 
  scale_y_continuous(expand = c(0,0), labels = scales::comma, n.breaks = 10)
```

# Mileage
```{r}
MilesByVehType <- as.data.table(read_excel("~/Documents/GitHub/SustainableMotoringIndex/KSIs/tra0101-miles-by-vehicle-type.xlsx", sheet = "TRA0101", skip = 4))
MilesbyRoadClass <- as.data.table(read_excel("CSV/tra0102-miles-by-road-class.xlsx", sheet = "TRA0102", skip = 4))

setnames(MilesByVehType, c("Year", "Notes", "Units", "Cars and Taxis", "Light Commercial Vehicles [note 1]", "Heavy Goods Vehicles [note 2]", "Other Vehicles: Motorcycles", "Other Vehicles: Buses and Coaches", "Total Other Vehicles [note 3]", "All Motor Vehicles"), 
         c("Year", "Notes", "Units", "Cars and taxis", "Light commercial vehicles", "Heavy goods vehicles", "Motorcycles", "Buses and coaches", "Total other vehicles", "All motor vehicles"))

setnames(MilesbyRoadClass, c("Year", "Notes", "Units", "Major Roads: Motorway [note 1]", "Major Roads: Rural 'A' Roads [note 2]", "Major Roads: Urban 'A' Roads [note 2]", "Major Roads: All 'A' Roads", "All Major Roads", "Minor Roads: Rural [note 2]", "Minor Roads: Urban [note 2]", "All Minor Roads", "All Roads"), 
         c("Year", "Notes", "Units", "Motorways", "Rural A roads", "Urban A roads", "All A roads", "All major roads", "Rural minor roads", "Urban minor roads", "All minor roads", "All roads"))


MilesByVehType <- melt(MilesByVehType[,.(Year, `Cars and taxis`, `Light commercial vehicles`, `Heavy goods vehicles`, Motorcycles, `Buses and coaches`, `Total other vehicles`, `All motor vehicles`)], id.vars = c("Year"))
setnames(MilesByVehType, c("variable", "value"), c("Vehicle type", "Miles driven"))
MilesByVehType<-MilesByVehType[, `Vehicle type`:=as.character(`Vehicle type`)]


MilesbyRoadClass <- melt(MilesbyRoadClass[,.(Year, Motorways, `Rural A roads`, `Urban A roads`, `All A roads`, `All major roads`, `Rural minor roads`, `Urban minor roads`, `All minor roads`, `All roads`)], id.vars = "Year")
MilesbyRoadClass <- MilesbyRoadClass[,variable:=as.character(variable)]
setnames(MilesbyRoadClass, c("variable", "value"), c("Road type", "Miles driven"))
```

```{r}
ggplot(MilesByVehType, aes(x = Year, y = `Miles driven`, colour = `Vehicle type`)) + 
  geom_line() + 
  theme_classic() + 
  labs(title = "Total billion miles travelled by vehicle type", y = "Miles travelled (billions)", x = "Year") +
  scale_colour_manual("", values = .VehicleColours) + 
  scale_x_continuous(n.breaks = 20, expand = c(0,0)) + 
  scale_y_continuous(n.breaks = 20, expand = c(0,0)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), plot.subtitle = element_text(hjust = 0, face = "italic"), axis.text.x=element_text(angle = 45, hjust=1), plot.caption = element_text(face = "italic"), legend.position = "bottom")
```

```{r}
ggplot(MilesbyRoadClass[`Road type` %in% c("Motorways", "Rural A roads", "Urban A roads", "Rural minor roads", "Urban minor roads")], aes(x = Year, y = `Miles driven`, colour = `Road type`)) + 
  geom_line() + 
  theme_classic() + 
  labs(title = "Total billion miles travelled by road type", y = "Miles travelled (billions)", x = "Year") +
  scale_colour_manual("", values = .RoadClassColours) + 
  scale_x_continuous(n.breaks = 20, expand = c(0,0)) + 
  scale_y_continuous(n.breaks = 20, expand = c(0,0)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), plot.subtitle = element_text(hjust = 0, face = "italic"), axis.text.x=element_text(angle = 45, hjust=1), plot.caption = element_text(face = "italic"), legend.position = "bottom")
```
