---
title: "Set-up"
author: "ruby"
date: "2024-11-11"
output: pdf_document
---

#Set up
```{r}
if(!require("pacman")) install.packages("pacman")
pacman::p_load(data.table, lubridate, ggplot2, patchwork, readxl, readr, RACFfunctions, scales, utils)
options(scipen = 100)
```

```{r}
MilesByVehType <- as.data.table(read_excel("~/Documents/GitHub/SustainableMotoringIndex/KSIs/tra0101-miles-by-vehicle-type.xlsx", sheet = "TRA0101", skip = 4))
MilesbyRoadClass <- as.data.table(read_excel("CSV/tra0102-miles-by-road-class.xlsx", sheet = "TRA0102", skip = 4))

setnames(MilesByVehType, c("Year", "Notes", "Units", "Cars and Taxis", "Light Commercial Vehicles [note 1]", "Heavy Goods Vehicles [note 2]", "Other Vehicles: Motorcycles", "Other Vehicles: Buses and Coaches", "Total Other Vehicles [note 3]", "All Motor Vehicles"), 
         c("Year", "Notes", "Units", "Cars and taxis", "Light commercial vehicles", "Heavy goods vehicles", "Motorcycles", "Buses and coaches", "Total other vehicles", "All motor vehicles"))

setnames(MilesbyRoadClass, c("Year", "Notes", "Units", "Major Roads: Motorway [note 1]", "Major Roads: Rural 'A' Roads [note 2]", "Major Roads: Urban 'A' Roads [note 2]", "Major Roads: All 'A' Roads", "All Major Roads", "Minor Roads: Rural [note 2]", "Minor Roads: Urban [note 2]", "All Minor Roads", "All Roads"), 
         c("Year", "Notes", "Units", "Motorways", "Rural A roads", "Urban A roads", "All A roads", "All major roads", "Rural minor roads", "Urban minor roads", "All minor roads", "All roads"))


MilesByVehType <- melt(MilesByVehType[,.(Year, `Cars and taxis`, `Light commercial vehicles`, `Heavy goods vehicles`, Motorcycles, `Buses and coaches`, `Total other vehicles`, `All motor vehicles`)], id.vars = c("Year"))
setnames(MilesByVehType, c("variable", "value"), c("Vehicle type", "Miles driven"))
MilesByVehType<-MilesByVehType[, `Vehicle type`:=as.character(`Vehicle type`)]


MilesbyRoadClass <- melt(MilesbyRoadClass[,.(Year, Motorways, `Rural A roads`, `Urban A roads`, `All A roads`, `All major roads`, `Rural minor roads`, `Urban minor roads`, `All minor roads`, `All roads`)], id.vars = "Year")
MilesbyRoadClass <- MilesbyRoadClass[,variable:=as.character(variable)]
setnames(MilesbyRoadClass, c("variable", "value"), c("Road type", "Miles driven"))
```

```{r}
ggplot(MilesByVehType, aes(x = Year, y = `Miles driven`, colour = `Vehicle type`)) + 
  geom_line() + 
  theme_classic() + 
  labs(title = "Total billion miles travelled by vehicle type", y = "Miles travelled (billions)", x = "Year") +
  scale_colour_manual("", values = .VehicleColours) + 
  scale_x_continuous(n.breaks = 20, expand = c(0,0)) + 
  scale_y_continuous(n.breaks = 20, expand = c(0,0)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), plot.subtitle = element_text(hjust = 0, face = "italic"), axis.text.x=element_text(angle = 45, hjust=1), plot.caption = element_text(face = "italic"), legend.position = "bottom")
```

```{r}
ggplot(MilesbyRoadClass[`Road type` %in% c("Motorways", "Rural A roads", "Urban A roads", "Rural minor roads", "Urban minor roads")], aes(x = Year, y = `Miles driven`, colour = `Road type`)) + 
  geom_line() + 
  theme_classic() + 
  labs(title = "Total billion miles travelled by road type", y = "Miles travelled (billions)", x = "Year") +
  scale_colour_manual("", values = .RoadClassColours) + 
  scale_x_continuous(n.breaks = 20, expand = c(0,0)) + 
  scale_y_continuous(n.breaks = 20, expand = c(0,0)) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), plot.subtitle = element_text(hjust = 0, face = "italic"), axis.text.x=element_text(angle = 45, hjust=1), plot.caption = element_text(face = "italic"), legend.position = "bottom")
```
